# Generated by Django 5.1.1 on 2025-09-05 04:34

import WebApp.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('assigned_bhw', models.CharField(blank=True, max_length=100, null=True)),
                ('health_center', models.CharField(blank=True, max_length=100, null=True)),
                ('zone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_established', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Upload an image for this announcement', null=True, upload_to=WebApp.models.announcement_image_upload_path)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'webapp_announcement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(default='Unknown', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('password', models.CharField(max_length=100)),
                ('user_role', models.CharField(max_length=100)),
                ('is_validated', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_notif_read', models.BooleanField(default=False)),
                ('must_change_password', models.BooleanField(default=False)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_accounts', to=settings.AUTH_USER_MODEL)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebApp.barangay')),
            ],
        ),
        migrations.CreateModel(
            name='BHW',
            fields=[
                ('bhw_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=100)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApp.barangay')),
            ],
        ),
        migrations.CreateModel(
            name='BNS',
            fields=[
                ('bns_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=100)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApp.barangay')),
            ],
        ),
        migrations.CreateModel(
            name='Midwife',
            fields=[
                ('midwife_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=100)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApp.barangay')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('nurse_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=100)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApp.barangay')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parent_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('must_change_password', models.BooleanField(default=True)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebApp.barangay')),
            ],
        ),
        migrations.CreateModel(
            name='ParentActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.barangay')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.parent')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Preschooler',
            fields=[
                ('preschooler_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('age', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('nutritional_status', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='preschoolers/')),
                ('birth_weight', models.FloatField(blank=True, null=True)),
                ('birth_height', models.FloatField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_notif_read', models.BooleanField(default=False)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApp.barangay')),
                ('bhw_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApp.bhw')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApp.parent')),
            ],
        ),
        migrations.AddField(
            model_name='parent',
            name='registered_preschoolers',
            field=models.ManyToManyField(blank=True, related_name='parents', to='WebApp.preschooler'),
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('immunization_id', models.AutoField(primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=100)),
                ('date_administered', models.DateField()),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApp.bhw')),
                ('preschooler_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.preschooler')),
            ],
        ),
        migrations.CreateModel(
            name='BMI',
            fields=[
                ('bmi_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('bmi_value', models.FloatField()),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('preschooler_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.preschooler')),
            ],
        ),
        migrations.CreateModel(
            name='PreschoolerActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preschooler_name', models.CharField(max_length=255)),
                ('activity', models.TextField()),
                ('performed_by', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.barangay')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default-profile.png', upload_to='profile_photos/')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_photo', to='WebApp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('temperature_id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature_value', models.FloatField()),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('preschooler_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.preschooler')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApp.bhw')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('doses', models.IntegerField(blank=True, null=True)),
                ('required_doses', models.IntegerField(blank=True, null=True)),
                ('scheduled_date', models.DateField()),
                ('next_vaccine_schedule', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled'), ('missed', 'Missed')], default='scheduled', max_length=20)),
                ('confirmed_by_parent', models.BooleanField(default=False)),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('reschedule_reason', models.TextField(blank=True, null=True)),
                ('stock_deducted', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
                ('lapsed', models.BooleanField(default=False)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_schedules', to='WebApp.bhw')),
                ('preschooler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_schedules', to='WebApp.preschooler')),
                ('scheduled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebApp.bhw')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100, unique=True)),
                ('total_stock', models.IntegerField(default=0)),
                ('available_stock', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_stocks', to='WebApp.barangay')),
            ],
            options={
                'unique_together': {('vaccine_name', 'barangay')},
            },
        ),
    ]
