# Generated by Django 5.2.4 on 2025-09-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preschooler',
            options={'ordering': ['-date_registered'], 'verbose_name': 'Preschooler', 'verbose_name_plural': 'Preschoolers'},
        ),
        migrations.AddField(
            model_name='preschooler',
            name='place_of_delivery',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Lying-in', 'Lying-in'), ('Hospital', 'Hospital'), ('Others', 'Others')], help_text='Place where delivery occurred', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='preschooler',
            name='type_of_birth',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('CS', 'Cesarean Section (CS)')], help_text='Type of delivery', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='preschooler',
            name='birth_height',
            field=models.FloatField(blank=True, help_text='Birth length/height in centimeters', null=True),
        ),
        migrations.AlterField(
            model_name='preschooler',
            name='birth_weight',
            field=models.FloatField(blank=True, help_text='Birth weight in kilograms', null=True),
        ),
        migrations.AlterField(
            model_name='preschooler',
            name='place_of_birth',
            field=models.CharField(blank=True, help_text='Place where the child was born', max_length=255, null=True),
        ),
    ]
