# Generated by Django 5.2.4 on 2025-09-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_alter_preschooler_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preschooler',
            name='time_of_birth',
            field=models.TimeField(blank=True, help_text='Time when the child was born (HH:MM)', null=True),
        ),
    ]
