# Generated by Django 5.2.4 on 2025-09-05 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_preschooler_time_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('completion_date', models.DateTimeField()),
                ('status', models.CharField(default='completed', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preschooler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_services', to='WebApp.preschooler')),
            ],
            options={
                'ordering': ['-completion_date'],
            },
        ),
    ]
